version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/backend
    owner: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_was.sh
      timeout: 60
      runas: ec2-user
  # JAVA_HOME과 PATH 설정을 명시적으로 로드
  AfterInstall:
    - location: /etc/profile.d/jdk.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 60
      runas: ec2-user