version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend
file_exists_behavior: OVERWRITE

permissions:
  - object: /scripts
    owner: root
    mode: 755
    type:
      - directory

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 60
      runas: root
#    - location: scripts/health_check.sh
#      timeout: 60
#      runas: ec2-user
#    - location: scripts/switch.sh
#      timeout: 60
#      runas: ec2-user