version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/backend
    owner: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 60
      runas: ec2-user